const crypto = require('crypto');
function send(res,status,body,headers={}){Object.entries(headers).forEach(([k,v])=>res.setHeader(k,v));res.status(status).json(body)}
function config(){const url=process.env.SUPABASE_URL,anon=process.env.SUPABASE_ANON_KEY,key=process.env.SUPABASE_SERVICE_ROLE_KEY,owner=process.env.OWNER_KEY||process.env.CIVILCAREER_OWNER_KEY||process.env.ADMIN_OWNER_KEY;if(!url||!anon||!key)throw Error('Alert service is not configured.');return{url,anon,key,owner}}
async function rest(path,opts={}){const{url,key}=config();const r=await fetch(`${url}/rest/v1/${path}`,{...opts,headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json',prefer:'return=representation',...(opts.headers||{})}});const text=await r.text();if(!r.ok)throw Error(text||'Database request failed.');return text?JSON.parse(text):[]}
async function userFromToken(req){const {url,anon}=config();const h=String(req.headers.authorization||'');if(!/^Bearer\s+[^\s]+$/i.test(h))return null;const token=h.replace(/^Bearer\s+/i,'');const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:anon,authorization:`Bearer ${token}`}});if(!r.ok)return null;const u=await r.json();return u&&u.id?{id:u.id,email:u.email||''}:null}
function owner(req){const {owner}=config();return !!owner&&String(req.headers['x-owner-key']||'')===owner}
function cleanEmail(v){const e=String(v||'').trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)?e:''}
function clean(v,max=180){return String(v??'').trim().slice(0,max)}
function alertPayload(b,u){const email=cleanEmail(u?.email||b.email);if(!email)throw Error('A valid email address is required.');const type=['all','private','government'].includes(String(b.alert_type))?String(b.alert_type):'all';const frequency=['daily','weekly'].includes(String(b.frequency))?String(b.frequency):'daily';return{email,user_id:u?.id||null,alert_type:type,keywords:clean(b.keywords,300),role:clean(b.role,120),location:clean(b.location,180),state:clean(b.state,100),city:clean(b.city,100),work_type:clean(b.work_type,80),frequency,active:b.active!==false}}
function token(){return crypto.randomBytes(24).toString('hex')}
function matchJob(a,j){const type=String(a.alert_type||'all').toLowerCase();const sector=String(j.sector||'').toLowerCase();if(type==='private'&&/(government|public sector)/i.test(sector))return false;if(type==='government'&&!/(government|public sector)/i.test(sector))return false;const hay=[j.role,j.job_title,j.title,j.company,j.company_name,j.description,j.skills,j.location,j.location_display,j.state,j.city,j.employment_type].join(' ').toLowerCase();const kws=String(a.keywords||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(kws.length&&!kws.some(k=>hay.includes(k)))return false;for(const key of ['role','location','state','city','work_type']){const v=String(a[key]||'').trim().toLowerCase();if(v&&!hay.includes(v))return false}return true}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','private, no-store');try{const u=await userFromToken(req);if(req.method==='GET'){if(owner(req)){const rows=await rest('job_alerts?select=id,user_id,email,alert_type,keywords,role,location,state,city,work_type,frequency,active,created_at,last_sent_at,last_evaluated_at&order=created_at.desc&limit=500');return send(res,200,{alerts:rows,admin:true})}if(!u)return send(res,401,{error:'Sign in required.'});const rows=await rest(`job_alerts?user_id=eq.${u.id}&select=id,email,alert_type,keywords,role,location,state,city,work_type,frequency,active,created_at,last_sent_at,last_evaluated_at&order=created_at.desc&limit=20`);return send(res,200,{alerts:rows})}
if(req.method==='POST'&&String(req.query?.action||'')==='evaluate'&&owner(req)){return evaluateAlerts(req,res)}
if(req.method==='POST'){const b=req.body||{};const p=alertPayload(b,u);p.unsubscribe_token=token();if(u){const existing=await rest(`job_alerts?user_id=eq.${u.id}&select=id&limit=1`);if(existing.length){await rest(`job_alerts?id=eq.${existing[0].id}`,{method:'PATCH',body:JSON.stringify({...p,last_evaluated_at:null})});return send(res,200,{saved:true,id:existing[0].id})}}
const rows=await rest('job_alerts',{method:'POST',body:JSON.stringify(p)});return send(res,200,{saved:true,id:rows[0]?.id||null})}
if(req.method==='PATCH'){if(!u)return send(res,401,{error:'Sign in required.'});const b=req.body||{};if(!b.id)return send(res,400,{error:'Alert id required.'});const p=alertPayload(b,u);const rows=await rest(`job_alerts?id=eq.${encodeURIComponent(b.id)}&user_id=eq.${u.id}`,{method:'PATCH',body:JSON.stringify({...p,last_evaluated_at:null})});return send(res,200,{saved:!!rows.length})}
if(req.method==='DELETE'){if(!u)return send(res,401,{error:'Sign in required.'});const id=String(req.body?.id||req.query?.id||'');if(!id)return send(res,400,{error:'Alert id required.'});await rest(`job_alerts?id=eq.${encodeURIComponent(id)}&user_id=eq.${u.id}`,{method:'DELETE'});return send(res,200,{deleted:true})}
if(req.method==='PUT'&&owner(req)){const b=req.body||{};const id=String(b.id||'');if(!id)return send(res,400,{error:'Alert id required.'});const rows=await rest(`job_alerts?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({active:b.active!==false})});return send(res,200,{updated:!!rows.length})}
return send(res,405,{error:'Method not allowed.'})}catch(e){return send(res,500,{error:e.message||'Alert request failed.'})}}
async function evaluateAlerts(req,res){const alerts=await rest('job_alerts?active=eq.true&select=id,email,user_id,alert_type,keywords,role,location,state,city,work_type,frequency,last_sent_at&limit=500');const now=new Date();const since=new Date(now.getTime()-48*3600000).toISOString();const jobs=await rest(`jobs?published=eq.true&or=(published_at.gte.${encodeURIComponent(since)},created_at.gte.${encodeURIComponent(since)})&select=id,slug,role,job_title,title,company,company_name,description,skills,location,location_display,state,city,employment_type,sector,published_at,created_at,expires_at&order=created_at.desc&limit=300`);let queued=0,matched=0;for(const a of alerts){const recent=jobs.filter(j=>matchJob(a,j));matched+=recent.length;for(const j of recent){const exists=await rest(`job_alert_deliveries?alert_id=eq.${a.id}&job_id=eq.${j.id}&select=id&limit=1`).catch(()=>[]);if(!exists.length){await rest('job_alert_deliveries',{method:'POST',body:JSON.stringify({alert_id:a.id,job_id:j.id,status:'pending'})}).catch(()=>{});queued++}}await rest(`job_alerts?id=eq.${a.id}`,{method:'PATCH',body:JSON.stringify({last_evaluated_at:now.toISOString()})}).catch(()=>{})}return send(res,200,{evaluated:alerts.length,jobs:jobs.length,matched,queued,delivery:'queued-only',message:'Notifications are queued for delivery; no email provider is invoked by this endpoint.'})}
