function send(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body));}
const buckets=new Map();
function rate(req){const ip=String(req.headers['x-forwarded-for']||req.headers['x-real-ip']||'unknown').split(',')[0].trim();const now=Date.now(),slot=buckets.get(ip)||{at:now,n:0};if(now-slot.at>3600000){slot.at=now;slot.n=0;}slot.n++;buckets.set(ip,slot);return slot.n<=5;}
function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Error('Contact service is not configured.');return{url,key};}
async function db(path,opts={}){const{url,key}=config();const r=await fetch(`${url}/rest/v1/${path}`,{...opts,headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json',prefer:'return=representation',...(opts.headers||{})}});const t=await r.text();if(!r.ok)throw Error(t||'Database request failed.');return t?JSON.parse(t):[];}
module.exports=async(req,res)=>{try{
 if(req.method==='GET'){if(!req.adminUser)return send(res,403,{error:'Administrator access denied.'});return send(res,200,{messages:await db('contact_messages?select=*&order=created_at.desc&limit=300')});}
 if(req.method==='PATCH'){if(!req.adminUser)return send(res,403,{error:'Administrator access denied.'});const id=String(req.body?.id||'');const status=String(req.body?.status||'');if(!id||!['New','Read','Resolved','Spam'].includes(status))return send(res,400,{error:'Invalid contact message update.'});const rows=await db(`contact_messages?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})});return send(res,200,{message:rows[0]});}
 if(req.method!=='POST')return send(res,405,{error:'Method not allowed.'});if(!rate(req))return send(res,429,{error:'Too many messages. Please try again later.'});const b=req.body||{};if(String(b.website||'').trim())return send(res,200,{sent:true});const name=String(b.name||'').trim().slice(0,120),email=String(b.email||'').trim().slice(0,200),message=String(b.message||'').trim().slice(0,4000);if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||message.length<10)return send(res,400,{error:'Enter your name, a valid email and a message of at least 10 characters.'});const row=await db('contact_messages',{method:'POST',body:JSON.stringify({name,email,message,status:'New'})});return send(res,201,{sent:true,message:row[0]});
}catch(e){return send(res,500,{error:e.message==='Contact service is not configured.'?e.message:'Could not submit your message.'});}};
